config/routes.rb
Rails.application.routes.draw do
  resources :mike_ann_kids

  resources :drinks

end

app/models/drink.rb
class Drink < ActiveRecord::Base
end

app/models/mike_ann_kid.rb
class MikeAnnKid < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:name, :temperature)
    end
end

app/controllers/mike_ann_kids_controller.rb
class MikeAnnKidsController < ApplicationController
  before_action :set_mike_ann_kid, only: [:show, :edit, :update, :destroy]

  # GET /mike_ann_kids
  # GET /mike_ann_kids.json
  def index
    @mike_ann_kids = MikeAnnKid.all
  end

  # GET /mike_ann_kids/1
  # GET /mike_ann_kids/1.json
  def show
  end

  # GET /mike_ann_kids/new
  def new
    @mike_ann_kid = MikeAnnKid.new
  end

  # GET /mike_ann_kids/1/edit
  def edit
  end

  # POST /mike_ann_kids
  # POST /mike_ann_kids.json
  def create
    @mike_ann_kid = MikeAnnKid.new(mike_ann_kid_params)

    respond_to do |format|
      if @mike_ann_kid.save
        format.html { redirect_to @mike_ann_kid, notice: 'Mike ann kid was successfully created.' }
        format.json { render :show, status: :created, location: @mike_ann_kid }
      else
        format.html { render :new }
        format.json { render json: @mike_ann_kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mike_ann_kids/1
  # PATCH/PUT /mike_ann_kids/1.json
  def update
    respond_to do |format|
      if @mike_ann_kid.update(mike_ann_kid_params)
        format.html { redirect_to @mike_ann_kid, notice: 'Mike ann kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @mike_ann_kid }
      else
        format.html { render :edit }
        format.json { render json: @mike_ann_kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mike_ann_kids/1
  # DELETE /mike_ann_kids/1.json
  def destroy
    @mike_ann_kid.destroy
    respond_to do |format|
      format.html { redirect_to mike_ann_kids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mike_ann_kid
      @mike_ann_kid = MikeAnnKid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mike_ann_kid_params
      params.require(:mike_ann_kid).permit(:first_name, :last_name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/mike_ann_kids_helper.rb
module MikeAnnKidsHelper
end

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.number_field :temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<h1>Listing drinks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinks.each do |drink| %>
      <tr>
        <td><%= drink.name %></td>
        <td><%= drink.temperature %></td>
        <td><%= link_to 'Show', drink %></td>
        <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
        <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drink.name %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @drink.temperature %>
</p>

<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysecondapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mike_ann_kids/_form.html.erb
<%= form_for(@mike_ann_kid) do |f| %>
  <% if @mike_ann_kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mike_ann_kid.errors.count, "error") %> prohibited this mike_ann_kid from being saved:</h2>

      <ul>
      <% @mike_ann_kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mike_ann_kids/edit.html.erb
<h1>Editing mike_ann_kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @mike_ann_kid %> |
<%= link_to 'Back', mike_ann_kids_path %>

app/views/mike_ann_kids/index.html.erb
<h1>Listing mike_ann_kids</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mike_ann_kids.each do |mike_ann_kid| %>
      <tr>
        <td><%= mike_ann_kid.first_name %></td>
        <td><%= mike_ann_kid.last_name %></td>
        <td><%= mike_ann_kid.age %></td>
        <td><%= link_to 'Show', mike_ann_kid %></td>
        <td><%= link_to 'Edit', edit_mike_ann_kid_path(mike_ann_kid) %></td>
        <td><%= link_to 'Destroy', mike_ann_kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mike ann kid', new_mike_ann_kid_path %>

app/views/mike_ann_kids/new.html.erb
<h1>New mike_ann_kid</h1>

<%= render 'form' %>

<%= link_to 'Back', mike_ann_kids_path %>

app/views/mike_ann_kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @mike_ann_kid.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @mike_ann_kid.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @mike_ann_kid.age %>
</p>

<%= link_to 'Edit', edit_mike_ann_kid_path(@mike_ann_kid) %> |
<%= link_to 'Back', mike_ann_kids_path %>